"""
Writer Service

Single integration point for the backend/pipeline.

Receives the analyst JSON output, runs the Writer Agent through watsonx.ai,
normalizes the result, exports MkDocs, and returns frontend-ready docs.

Expected input:
{
    "project_name": "...",
    "repo_context": {...},
    "bob_response": {...}
}

Returned output:
{
    "project_name": "...",
    "documentation_format": "markdown",
    "generated_at": "...",
    "pages": [...],
    "exports": {
        "mkdocs_available": true/false,
        "download_url": "..."
    }
}
"""

from agents.api.writer.writer_agent import run_writer_agent
from agents.api.writer.watsonx_writer_client import watsonx_llm_call
from agents.api.writer.mkdocs_exporter import export_mkdocs_project


def generate_writer_docs(input_data: dict, export_mkdocs: bool = True) -> dict:
    """
    Generate frontend-ready documentation from the analyst output JSON.

    Args:
        input_data: JSON generated by the analyst module.
        export_mkdocs: If True, generates MkDocs project and ZIP.

    Returns:
        frontend_docs dictionary ready for the frontend.
    """
    frontend_docs = run_writer_agent(input_data, watsonx_llm_call)

    if not export_mkdocs:
        return frontend_docs

    mkdocs_result = export_mkdocs_project(frontend_docs)

    frontend_docs["exports"] = {
        "mkdocs_available": mkdocs_result.get("mkdocs_available", False),
        "download_url": mkdocs_result.get("zip_path"),
    }

    return frontend_docs